#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrategyDeveloper_Ver_0._0._1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Alpha")]
	public partial class StockDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public StockDataDataContext() : 
				base(global::StrategyDeveloper_Ver_0._0._1.Properties.Settings.Default.AlphaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StockDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StockDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StockDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StockDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<_000001> _000001
		{
			get
			{
				return this.GetTable<_000001>();
			}
		}
		
		public System.Data.Linq.Table<_000007> _000007
		{
			get
			{
				return this.GetTable<_000007>();
			}
		}
		
		public System.Data.Linq.Table<_002685> _002685
		{
			get
			{
				return this.GetTable<_002685>();
			}
		}
		
		public System.Data.Linq.Table<_000835> _000835
		{
			get
			{
				return this.GetTable<_000835>();
			}
		}
		
		public System.Data.Linq.Table<_600804> _600804
		{
			get
			{
				return this.GetTable<_600804>();
			}
		}
		
		public System.Data.Linq.Table<_300342> _300342
		{
			get
			{
				return this.GetTable<_300342>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[000001]")]
	public partial class _000001
	{
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<decimal> _Oppr;
		
		private System.Nullable<decimal> _Hipr;
		
		private System.Nullable<decimal> _Lopr;
		
		private System.Nullable<decimal> _Clpr;
		
		private System.Nullable<decimal> _Trdsum;
		
		private System.Nullable<decimal> _Trdvol;
		
		private System.Nullable<float> _Alpha120d;
		
		private System.Nullable<float> _Beta120d;
		
		private System.Nullable<float> _StockRate;
		
		private System.Nullable<decimal> _AdjOppr2;
		
		private System.Nullable<decimal> _AdjHipr2;
		
		private System.Nullable<decimal> _AdjLopr2;
		
		private System.Nullable<decimal> _Adjclpr2;
		
		private System.Nullable<decimal> _DCFacPr;
		
		private string _CsrcIcCd1;
		
		private System.Nullable<decimal> _FullShr;
		
		private System.Nullable<decimal> _Trdshr;
		
		public _000001()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oppr", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> Oppr
		{
			get
			{
				return this._Oppr;
			}
			set
			{
				if ((this._Oppr != value))
				{
					this._Oppr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hipr", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> Hipr
		{
			get
			{
				return this._Hipr;
			}
			set
			{
				if ((this._Hipr != value))
				{
					this._Hipr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lopr", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> Lopr
		{
			get
			{
				return this._Lopr;
			}
			set
			{
				if ((this._Lopr != value))
				{
					this._Lopr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clpr", DbType="Decimal(14,4)")]
		public System.Nullable<decimal> Clpr
		{
			get
			{
				return this._Clpr;
			}
			set
			{
				if ((this._Clpr != value))
				{
					this._Clpr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trdsum", DbType="Decimal(19,2)")]
		public System.Nullable<decimal> Trdsum
		{
			get
			{
				return this._Trdsum;
			}
			set
			{
				if ((this._Trdsum != value))
				{
					this._Trdsum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trdvol", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Trdvol
		{
			get
			{
				return this._Trdvol;
			}
			set
			{
				if ((this._Trdvol != value))
				{
					this._Trdvol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alpha120d", DbType="Real")]
		public System.Nullable<float> Alpha120d
		{
			get
			{
				return this._Alpha120d;
			}
			set
			{
				if ((this._Alpha120d != value))
				{
					this._Alpha120d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Beta120d", DbType="Real")]
		public System.Nullable<float> Beta120d
		{
			get
			{
				return this._Beta120d;
			}
			set
			{
				if ((this._Beta120d != value))
				{
					this._Beta120d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockRate", DbType="Real")]
		public System.Nullable<float> StockRate
		{
			get
			{
				return this._StockRate;
			}
			set
			{
				if ((this._StockRate != value))
				{
					this._StockRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjOppr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjOppr2
		{
			get
			{
				return this._AdjOppr2;
			}
			set
			{
				if ((this._AdjOppr2 != value))
				{
					this._AdjOppr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjHipr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjHipr2
		{
			get
			{
				return this._AdjHipr2;
			}
			set
			{
				if ((this._AdjHipr2 != value))
				{
					this._AdjHipr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjLopr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjLopr2
		{
			get
			{
				return this._AdjLopr2;
			}
			set
			{
				if ((this._AdjLopr2 != value))
				{
					this._AdjLopr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adjclpr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> Adjclpr2
		{
			get
			{
				return this._Adjclpr2;
			}
			set
			{
				if ((this._Adjclpr2 != value))
				{
					this._Adjclpr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCFacPr", DbType="Decimal(14,4)")]
		public System.Nullable<decimal> DCFacPr
		{
			get
			{
				return this._DCFacPr;
			}
			set
			{
				if ((this._DCFacPr != value))
				{
					this._DCFacPr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CsrcIcCd1", DbType="VarChar(2)")]
		public string CsrcIcCd1
		{
			get
			{
				return this._CsrcIcCd1;
			}
			set
			{
				if ((this._CsrcIcCd1 != value))
				{
					this._CsrcIcCd1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullShr", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> FullShr
		{
			get
			{
				return this._FullShr;
			}
			set
			{
				if ((this._FullShr != value))
				{
					this._FullShr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trdshr", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Trdshr
		{
			get
			{
				return this._Trdshr;
			}
			set
			{
				if ((this._Trdshr != value))
				{
					this._Trdshr = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[000007]")]
	public partial class _000007
	{
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<decimal> _Oppr;
		
		private System.Nullable<decimal> _Hipr;
		
		private System.Nullable<decimal> _Lopr;
		
		private System.Nullable<decimal> _Clpr;
		
		private System.Nullable<decimal> _Trdsum;
		
		private System.Nullable<decimal> _Trdvol;
		
		private System.Nullable<float> _Alpha120d;
		
		private System.Nullable<float> _Beta120d;
		
		private System.Nullable<float> _StockRate;
		
		private System.Nullable<decimal> _AdjOppr2;
		
		private System.Nullable<decimal> _AdjHipr2;
		
		private System.Nullable<decimal> _AdjLopr2;
		
		private System.Nullable<decimal> _AdjClpr2;
		
		private System.Nullable<decimal> _DCFacPr;
		
		private string _CsrcIcCd1;
		
		private System.Nullable<decimal> _FullShr;
		
		private System.Nullable<decimal> _Trdshr;
		
		public _000007()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oppr", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> Oppr
		{
			get
			{
				return this._Oppr;
			}
			set
			{
				if ((this._Oppr != value))
				{
					this._Oppr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hipr", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> Hipr
		{
			get
			{
				return this._Hipr;
			}
			set
			{
				if ((this._Hipr != value))
				{
					this._Hipr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lopr", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> Lopr
		{
			get
			{
				return this._Lopr;
			}
			set
			{
				if ((this._Lopr != value))
				{
					this._Lopr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clpr", DbType="Decimal(14,4)")]
		public System.Nullable<decimal> Clpr
		{
			get
			{
				return this._Clpr;
			}
			set
			{
				if ((this._Clpr != value))
				{
					this._Clpr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trdsum", DbType="Decimal(19,2)")]
		public System.Nullable<decimal> Trdsum
		{
			get
			{
				return this._Trdsum;
			}
			set
			{
				if ((this._Trdsum != value))
				{
					this._Trdsum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trdvol", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Trdvol
		{
			get
			{
				return this._Trdvol;
			}
			set
			{
				if ((this._Trdvol != value))
				{
					this._Trdvol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alpha120d", DbType="Real")]
		public System.Nullable<float> Alpha120d
		{
			get
			{
				return this._Alpha120d;
			}
			set
			{
				if ((this._Alpha120d != value))
				{
					this._Alpha120d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Beta120d", DbType="Real")]
		public System.Nullable<float> Beta120d
		{
			get
			{
				return this._Beta120d;
			}
			set
			{
				if ((this._Beta120d != value))
				{
					this._Beta120d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockRate", DbType="Real")]
		public System.Nullable<float> StockRate
		{
			get
			{
				return this._StockRate;
			}
			set
			{
				if ((this._StockRate != value))
				{
					this._StockRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjOppr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjOppr2
		{
			get
			{
				return this._AdjOppr2;
			}
			set
			{
				if ((this._AdjOppr2 != value))
				{
					this._AdjOppr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjHipr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjHipr2
		{
			get
			{
				return this._AdjHipr2;
			}
			set
			{
				if ((this._AdjHipr2 != value))
				{
					this._AdjHipr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjLopr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjLopr2
		{
			get
			{
				return this._AdjLopr2;
			}
			set
			{
				if ((this._AdjLopr2 != value))
				{
					this._AdjLopr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjClpr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjClpr2
		{
			get
			{
				return this._AdjClpr2;
			}
			set
			{
				if ((this._AdjClpr2 != value))
				{
					this._AdjClpr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCFacPr", DbType="Decimal(14,4)")]
		public System.Nullable<decimal> DCFacPr
		{
			get
			{
				return this._DCFacPr;
			}
			set
			{
				if ((this._DCFacPr != value))
				{
					this._DCFacPr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CsrcIcCd1", DbType="VarChar(2)")]
		public string CsrcIcCd1
		{
			get
			{
				return this._CsrcIcCd1;
			}
			set
			{
				if ((this._CsrcIcCd1 != value))
				{
					this._CsrcIcCd1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullShr", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> FullShr
		{
			get
			{
				return this._FullShr;
			}
			set
			{
				if ((this._FullShr != value))
				{
					this._FullShr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trdshr", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Trdshr
		{
			get
			{
				return this._Trdshr;
			}
			set
			{
				if ((this._Trdshr != value))
				{
					this._Trdshr = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[002685]")]
	public partial class _002685
	{
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<decimal> _Oppr;
		
		private System.Nullable<decimal> _Hipr;
		
		private System.Nullable<decimal> _Lopr;
		
		private System.Nullable<decimal> _Clpr;
		
		private System.Nullable<decimal> _Trdsum;
		
		private System.Nullable<decimal> _Trdvol;
		
		private System.Nullable<decimal> _AdjOppr2;
		
		private System.Nullable<decimal> _AdjHipr2;
		
		private System.Nullable<decimal> _AdjLopr2;
		
		private System.Nullable<decimal> _AdjClpr2;
		
		private System.Nullable<decimal> _DCFacPr;
		
		private string _CsrcIcCd1;
		
		private System.Nullable<decimal> _FullShr;
		
		private System.Nullable<decimal> _Trdshr;
		
		public _002685()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oppr", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> Oppr
		{
			get
			{
				return this._Oppr;
			}
			set
			{
				if ((this._Oppr != value))
				{
					this._Oppr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hipr", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> Hipr
		{
			get
			{
				return this._Hipr;
			}
			set
			{
				if ((this._Hipr != value))
				{
					this._Hipr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lopr", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> Lopr
		{
			get
			{
				return this._Lopr;
			}
			set
			{
				if ((this._Lopr != value))
				{
					this._Lopr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clpr", DbType="Decimal(14,4)")]
		public System.Nullable<decimal> Clpr
		{
			get
			{
				return this._Clpr;
			}
			set
			{
				if ((this._Clpr != value))
				{
					this._Clpr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trdsum", DbType="Decimal(19,2)")]
		public System.Nullable<decimal> Trdsum
		{
			get
			{
				return this._Trdsum;
			}
			set
			{
				if ((this._Trdsum != value))
				{
					this._Trdsum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trdvol", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Trdvol
		{
			get
			{
				return this._Trdvol;
			}
			set
			{
				if ((this._Trdvol != value))
				{
					this._Trdvol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjOppr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjOppr2
		{
			get
			{
				return this._AdjOppr2;
			}
			set
			{
				if ((this._AdjOppr2 != value))
				{
					this._AdjOppr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjHipr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjHipr2
		{
			get
			{
				return this._AdjHipr2;
			}
			set
			{
				if ((this._AdjHipr2 != value))
				{
					this._AdjHipr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjLopr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjLopr2
		{
			get
			{
				return this._AdjLopr2;
			}
			set
			{
				if ((this._AdjLopr2 != value))
				{
					this._AdjLopr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjClpr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjClpr2
		{
			get
			{
				return this._AdjClpr2;
			}
			set
			{
				if ((this._AdjClpr2 != value))
				{
					this._AdjClpr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCFacPr", DbType="Decimal(14,4)")]
		public System.Nullable<decimal> DCFacPr
		{
			get
			{
				return this._DCFacPr;
			}
			set
			{
				if ((this._DCFacPr != value))
				{
					this._DCFacPr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CsrcIcCd1", DbType="VarChar(2)")]
		public string CsrcIcCd1
		{
			get
			{
				return this._CsrcIcCd1;
			}
			set
			{
				if ((this._CsrcIcCd1 != value))
				{
					this._CsrcIcCd1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullShr", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> FullShr
		{
			get
			{
				return this._FullShr;
			}
			set
			{
				if ((this._FullShr != value))
				{
					this._FullShr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trdshr", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Trdshr
		{
			get
			{
				return this._Trdshr;
			}
			set
			{
				if ((this._Trdshr != value))
				{
					this._Trdshr = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[000835]")]
	public partial class _000835
	{
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<decimal> _Oppr;
		
		private System.Nullable<decimal> _Hipr;
		
		private System.Nullable<decimal> _Lopr;
		
		private System.Nullable<decimal> _Clpr;
		
		private System.Nullable<decimal> _Trdsum;
		
		private System.Nullable<decimal> _Trdvol;
		
		private System.Nullable<decimal> _AdjOppr2;
		
		private System.Nullable<decimal> _AdjHipr2;
		
		private System.Nullable<decimal> _AdjLopr2;
		
		private System.Nullable<decimal> _AdjClpr2;
		
		private System.Nullable<decimal> _DCFacPr;
		
		private string _CsrcIcCd1;
		
		private System.Nullable<decimal> _FullShr;
		
		private System.Nullable<decimal> _Trdshr;
		
		public _000835()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oppr", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> Oppr
		{
			get
			{
				return this._Oppr;
			}
			set
			{
				if ((this._Oppr != value))
				{
					this._Oppr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hipr", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> Hipr
		{
			get
			{
				return this._Hipr;
			}
			set
			{
				if ((this._Hipr != value))
				{
					this._Hipr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lopr", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> Lopr
		{
			get
			{
				return this._Lopr;
			}
			set
			{
				if ((this._Lopr != value))
				{
					this._Lopr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clpr", DbType="Decimal(14,4)")]
		public System.Nullable<decimal> Clpr
		{
			get
			{
				return this._Clpr;
			}
			set
			{
				if ((this._Clpr != value))
				{
					this._Clpr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trdsum", DbType="Decimal(19,2)")]
		public System.Nullable<decimal> Trdsum
		{
			get
			{
				return this._Trdsum;
			}
			set
			{
				if ((this._Trdsum != value))
				{
					this._Trdsum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trdvol", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Trdvol
		{
			get
			{
				return this._Trdvol;
			}
			set
			{
				if ((this._Trdvol != value))
				{
					this._Trdvol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjOppr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjOppr2
		{
			get
			{
				return this._AdjOppr2;
			}
			set
			{
				if ((this._AdjOppr2 != value))
				{
					this._AdjOppr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjHipr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjHipr2
		{
			get
			{
				return this._AdjHipr2;
			}
			set
			{
				if ((this._AdjHipr2 != value))
				{
					this._AdjHipr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjLopr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjLopr2
		{
			get
			{
				return this._AdjLopr2;
			}
			set
			{
				if ((this._AdjLopr2 != value))
				{
					this._AdjLopr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjClpr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjClpr2
		{
			get
			{
				return this._AdjClpr2;
			}
			set
			{
				if ((this._AdjClpr2 != value))
				{
					this._AdjClpr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCFacPr", DbType="Decimal(14,4)")]
		public System.Nullable<decimal> DCFacPr
		{
			get
			{
				return this._DCFacPr;
			}
			set
			{
				if ((this._DCFacPr != value))
				{
					this._DCFacPr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CsrcIcCd1", DbType="VarChar(2)")]
		public string CsrcIcCd1
		{
			get
			{
				return this._CsrcIcCd1;
			}
			set
			{
				if ((this._CsrcIcCd1 != value))
				{
					this._CsrcIcCd1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullShr", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> FullShr
		{
			get
			{
				return this._FullShr;
			}
			set
			{
				if ((this._FullShr != value))
				{
					this._FullShr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trdshr", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Trdshr
		{
			get
			{
				return this._Trdshr;
			}
			set
			{
				if ((this._Trdshr != value))
				{
					this._Trdshr = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[600804]")]
	public partial class _600804
	{
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<decimal> _Oppr;
		
		private System.Nullable<decimal> _Hipr;
		
		private System.Nullable<decimal> _Lopr;
		
		private System.Nullable<decimal> _Clpr;
		
		private System.Nullable<decimal> _Trdsum;
		
		private System.Nullable<decimal> _Trdvol;
		
		private System.Nullable<decimal> _AdjOppr2;
		
		private System.Nullable<decimal> _AdjHipr2;
		
		private System.Nullable<decimal> _AdjLopr2;
		
		private System.Nullable<decimal> _AdjClpr2;
		
		private System.Nullable<decimal> _DCFacPr;
		
		private string _CsrcIcCd1;
		
		private System.Nullable<decimal> _FullShr;
		
		private System.Nullable<decimal> _Trdshr;
		
		public _600804()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oppr", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> Oppr
		{
			get
			{
				return this._Oppr;
			}
			set
			{
				if ((this._Oppr != value))
				{
					this._Oppr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hipr", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> Hipr
		{
			get
			{
				return this._Hipr;
			}
			set
			{
				if ((this._Hipr != value))
				{
					this._Hipr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lopr", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> Lopr
		{
			get
			{
				return this._Lopr;
			}
			set
			{
				if ((this._Lopr != value))
				{
					this._Lopr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clpr", DbType="Decimal(14,4)")]
		public System.Nullable<decimal> Clpr
		{
			get
			{
				return this._Clpr;
			}
			set
			{
				if ((this._Clpr != value))
				{
					this._Clpr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trdsum", DbType="Decimal(19,2)")]
		public System.Nullable<decimal> Trdsum
		{
			get
			{
				return this._Trdsum;
			}
			set
			{
				if ((this._Trdsum != value))
				{
					this._Trdsum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trdvol", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Trdvol
		{
			get
			{
				return this._Trdvol;
			}
			set
			{
				if ((this._Trdvol != value))
				{
					this._Trdvol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjOppr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjOppr2
		{
			get
			{
				return this._AdjOppr2;
			}
			set
			{
				if ((this._AdjOppr2 != value))
				{
					this._AdjOppr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjHipr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjHipr2
		{
			get
			{
				return this._AdjHipr2;
			}
			set
			{
				if ((this._AdjHipr2 != value))
				{
					this._AdjHipr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjLopr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjLopr2
		{
			get
			{
				return this._AdjLopr2;
			}
			set
			{
				if ((this._AdjLopr2 != value))
				{
					this._AdjLopr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjClpr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjClpr2
		{
			get
			{
				return this._AdjClpr2;
			}
			set
			{
				if ((this._AdjClpr2 != value))
				{
					this._AdjClpr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCFacPr", DbType="Decimal(14,4)")]
		public System.Nullable<decimal> DCFacPr
		{
			get
			{
				return this._DCFacPr;
			}
			set
			{
				if ((this._DCFacPr != value))
				{
					this._DCFacPr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CsrcIcCd1", DbType="VarChar(2)")]
		public string CsrcIcCd1
		{
			get
			{
				return this._CsrcIcCd1;
			}
			set
			{
				if ((this._CsrcIcCd1 != value))
				{
					this._CsrcIcCd1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullShr", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> FullShr
		{
			get
			{
				return this._FullShr;
			}
			set
			{
				if ((this._FullShr != value))
				{
					this._FullShr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trdshr", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Trdshr
		{
			get
			{
				return this._Trdshr;
			}
			set
			{
				if ((this._Trdshr != value))
				{
					this._Trdshr = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[300342]")]
	public partial class _300342
	{
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<decimal> _Oppr;
		
		private System.Nullable<decimal> _Hipr;
		
		private System.Nullable<decimal> _Lopr;
		
		private System.Nullable<decimal> _Clpr;
		
		private System.Nullable<decimal> _Trdsum;
		
		private System.Nullable<decimal> _Trdvol;
		
		private System.Nullable<decimal> _AdjOppr2;
		
		private System.Nullable<decimal> _AdjHipr2;
		
		private System.Nullable<decimal> _AdjLopr2;
		
		private System.Nullable<decimal> _AdjClpr2;
		
		private System.Nullable<decimal> _DCFacPr;
		
		private string _CsrcIcCd1;
		
		private System.Nullable<decimal> _FullShr;
		
		private System.Nullable<decimal> _Trdshr;
		
		public _300342()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oppr", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> Oppr
		{
			get
			{
				return this._Oppr;
			}
			set
			{
				if ((this._Oppr != value))
				{
					this._Oppr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hipr", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> Hipr
		{
			get
			{
				return this._Hipr;
			}
			set
			{
				if ((this._Hipr != value))
				{
					this._Hipr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lopr", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> Lopr
		{
			get
			{
				return this._Lopr;
			}
			set
			{
				if ((this._Lopr != value))
				{
					this._Lopr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clpr", DbType="Decimal(14,4)")]
		public System.Nullable<decimal> Clpr
		{
			get
			{
				return this._Clpr;
			}
			set
			{
				if ((this._Clpr != value))
				{
					this._Clpr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trdsum", DbType="Decimal(19,2)")]
		public System.Nullable<decimal> Trdsum
		{
			get
			{
				return this._Trdsum;
			}
			set
			{
				if ((this._Trdsum != value))
				{
					this._Trdsum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trdvol", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Trdvol
		{
			get
			{
				return this._Trdvol;
			}
			set
			{
				if ((this._Trdvol != value))
				{
					this._Trdvol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjOppr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjOppr2
		{
			get
			{
				return this._AdjOppr2;
			}
			set
			{
				if ((this._AdjOppr2 != value))
				{
					this._AdjOppr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjHipr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjHipr2
		{
			get
			{
				return this._AdjHipr2;
			}
			set
			{
				if ((this._AdjHipr2 != value))
				{
					this._AdjHipr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjLopr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjLopr2
		{
			get
			{
				return this._AdjLopr2;
			}
			set
			{
				if ((this._AdjLopr2 != value))
				{
					this._AdjLopr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjClpr2", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> AdjClpr2
		{
			get
			{
				return this._AdjClpr2;
			}
			set
			{
				if ((this._AdjClpr2 != value))
				{
					this._AdjClpr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCFacPr", DbType="Decimal(14,4)")]
		public System.Nullable<decimal> DCFacPr
		{
			get
			{
				return this._DCFacPr;
			}
			set
			{
				if ((this._DCFacPr != value))
				{
					this._DCFacPr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CsrcIcCd1", DbType="VarChar(2)")]
		public string CsrcIcCd1
		{
			get
			{
				return this._CsrcIcCd1;
			}
			set
			{
				if ((this._CsrcIcCd1 != value))
				{
					this._CsrcIcCd1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullShr", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> FullShr
		{
			get
			{
				return this._FullShr;
			}
			set
			{
				if ((this._FullShr != value))
				{
					this._FullShr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trdshr", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Trdshr
		{
			get
			{
				return this._Trdshr;
			}
			set
			{
				if ((this._Trdshr != value))
				{
					this._Trdshr = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
